
if(!require(maptools)) install.packages('maptools',repos='http://cran.csiro.au');require(maptools)   
 if(!require(uncompress)) install.packages('uncompress',repos='http://cran.csiro.au');require(uncompress)
 source('~/tools/connect2postgres.r')
 delphe <- connect2postgres(hostip='130.56.102.41',user='ivan_hanigan',db='delphe')
#  delphe <- connect2postgres(hostip='192.168.2.7',user='ivan_hanigan',db='digby')
# uncomment in run file so that can be sourced?
 source('~/tools/load2postgres.r')     
 source('~/tools/df2ddi.r')

vars<-c('variable,measure,timestep
rainfall,totals,daily
temperature,maxave,daily
temperature,minave,daily
vprp,vprph09,daily
vprp,vprph15,daily
solar,solarave,daily
ndvi,ndviave,month
')
vars<-read.csv(textConnection(vars))

# newnode get_data
 get_data<-function(variable,measure,timestep,startdate,enddate){
  url="http://www.bom.gov.au/web03/ncc/www/awap/{variable}/{measure}/{timestep}/grid/0.05/history/nat/{startdate}{enddate}.grid.Z" 
  url=gsub("{variable}",variable,url,fixed=TRUE)
  url=gsub("{measure}",measure,url,fixed=TRUE)
  url=gsub("{timestep}",timestep,url,fixed=TRUE)
  url=gsub("{startdate}",startdate,url,fixed=TRUE)
  url=gsub("{enddate}",enddate,url,fixed=TRUE)
  download.file(url,sprintf("%s_%s%s.grid.Z",measure,startdate,enddate),mode="wb")
  }

# newnode get_data_range
 get_data_range<-function(variable,measure,timestep,startdate,enddate){
  thisdate<-startdate
  while (thisdate<=enddate){
   get_data(variable,measure,timestep,format(as.POSIXct(thisdate),"%Y%m%d"),format(as.POSIXct(thisdate),"%Y%m%d"))
   thisdate<-thisdate+as.double(as.difftime(1,units="days"),units="secs")
   }
 }

#Modified from maptools package
#Reads only the specified number of data items, ignoring BOM's wierd footer
 read.asciigrid2<-function (fname, as.image = FALSE, plot.image = FALSE, colname = fname, proj4string = CRS(as.character(NA))) {
  t = file(fname, "r")
  l5 = readLines(t, n = 6)
  l5s = strsplit(l5, "\\s+", perl = T)
  xllcenter = yllcenter = xllcorner = yllcorner = as.numeric(NA)
  for (i in 1:6) {
     fieldname = casefold(l5s[[i]][1])
     if (length(grep("ncols", fieldname))) 
         ncols = as.numeric(l5s[[i]][2])
     if (length(grep("nrows", fieldname))) 
         nrows = as.numeric(l5s[[i]][2])
     if (length(grep("xllcorner", fieldname))) 
         xllcorner = as.numeric(l5s[[i]][2])
     if (length(grep("yllcorner", fieldname))) 
         yllcorner = as.numeric(l5s[[i]][2])
     if (length(grep("xllcenter", fieldname))) 
         xllcenter = as.numeric(l5s[[i]][2])
     if (length(grep("yllcenter", fieldname))) 
         yllcenter = as.numeric(l5s[[i]][2])
     if (length(grep("cellsize", fieldname))) 
         cellsize = as.numeric(l5s[[i]][2])
     if (length(grep("nodata_value", fieldname))) 
         nodata.value = as.numeric(l5s[[i]][2])
 }
 if (is.na(xllcorner) && !is.na(xllcenter)) 
     xllcorner = xllcenter - 0.5 * cellsize
 else xllcenter = xllcorner + 0.5 * cellsize
 if (is.na(yllcorner) && !is.na(yllcenter)) 
     yllcorner = yllcenter - 0.5 * cellsize
 else yllcenter = yllcorner + 0.5 * cellsize
 map = scan(t, as.numeric(0), quiet = TRUE,nmax=nrows*ncols)
 close(t)
 if (length(as.vector(map)) != nrows * ncols) 
     stop("dimensions of map do not match that of header")
 map[map == nodata.value] = NA
 if (as.image) {
     img = matrix(map, ncols, nrows)[, nrows:1]
     img = list(z = img, x = xllcorner + cellsize * ((1:ncols) - 
         0.5), y = yllcorner + cellsize * ((1:nrows) - 0.5))
     if (plot.image) {
         image(img, asp = 1)
         return(invisible(img))
     }
     else return(img)
 }
 df = data.frame(map)
 names(df) = colname
 grid = GridTopology(c(xllcenter, yllcenter), rep(cellsize, 
     2), c(ncols, nrows))
 SpatialGridDataFrame(grid, data = df, proj4string = proj4string)
 }

# filename must be in format generated by get_data: variable_{startdate}{enddate}
 grid2csv<-function(filename){
        variable<-strsplit(filename,"_")[[1]][1]
        year<-as.numeric(substr(strsplit(filename,"_")[[1]][2],1,4))
        month<-as.numeric(substr(strsplit(filename,"_")[[1]][2],5,6))
        day<-as.numeric(substr(strsplit(filename,"_")[[1]][2],7,8))
        csv_filename<-sub("grid","csv",filename)
        d<-read.asciigrid2(filename)
        #image(d)
        e<-as.data.frame(d)
        names(e)<-c(variable,"long","lat")
        e$year<-year
        e$month<-month
        e$day<-day
        write.csv(e,csv_filename,row.names=FALSE,na="")
 }
